local rendercam=require "rendercam.rendercam"

go.property("smooth_duration", 1)

function init(self)
	print(msg.url())
end
function on_message(self, message_id, message, sender)
	if message_id==hash("update") then
		self.smooth_duration=70/vmath.length(message.vel)
		go.cancel_animations(".", "position")
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, go.get_position("player"), go.EASING_LINEAR, self.smooth_duration)
	end
	
end