go.property("direction", vmath.vector3())
go.property("force", 0)
go.property("gravity", vmath.vector3(0,-10,0))
function init(self)
	print(self.force)
	self.vel=self.force*self.direction
	go.animate(".", "rotation", go.PLAYBACK_LOOP_FORWARD, vmath.quat_rotation_z(-1.57), go.EASING_LINEAR, 0.2)
end

function update(self, dt)
	local pos=go.get_position()+self.vel*dt
	go.set_position(pos)
	self.vel=self.vel+self.gravity
end